fruits = ['orange', 'apple', 'banana', 'kiwi', 'apple']
print(fruits.count('apple'))
print(fruits.count('kiwi'))
print(fruits.index('apple', 2))
print(fruits.reverse())
print(fruits)
fruits.append('grape')
print(fruits.sort())
fruits.pop()
print(fruits)